/* ===== Genomes & Proteins: Part C (prediction, design, open problems, quiz) ===== */
const freshCanvas=w=>{const oc=w.querySelector('canvas');const nc=oc.cloneNode(false);oc.replaceWith(nc);return nc};
/* ===== g11: history timeline ===== */
SCENES.push({id:'g11',belt:2,mood:'think',title:'The Prediction Problem: a 60-Year Timeline',
html:`<p class="lead">Walk the timeline (arrow buttons, or click a milestone and drag to pan). Right-drag or two fingers pan; scroll zooms.</p>
<div class="grid"><div class="card">${mkCv('clamp(240px,38vh,360px)')}<div class="row"><button class="btn sec" id="tp">◀ Earlier</button><button class="btn sec" id="tn">Later ▶</button></div></div><div class="card info" id="gi"></div></div>
<div class="card" style="margin-top:12px"><b>Why we needed prediction</b><div class="row" style="margin:6px 0"><span style="width:230px;font-size:13px">Known protein sequences (UniProt)</span><div class="bar" style="flex:1"><i style="width:100%"></i></div><b style="width:110px">≈ 250 million</b></div><div class="row" style="margin:6px 0"><span style="width:230px;font-size:13px">Experimentally solved structures (PDB)</span><div class="bar" style="flex:1"><i style="width:.3%;min-width:3px"></i></div><b style="width:110px">≈ 230 thousand</b></div>
<div class="mini">Experiments (X-ray crystallography, NMR, cryo-EM) can take months or years per protein. Prediction scores: <b>GDT_TS</b> ≈ the percentage of residues placed within a small distance of the true position (≈ 90+ is competitive with experiment). Best CASP free-modelling scores: ≈ 40 (2016), ≈ 58 (AlphaFold, 2018), <b>92.4 median (AlphaFold2, 2020)</b>. Early numbers are approximate.</div></div>`,
init(w){const M=[{y:1958,t:'Kendrew: first protein structure',d:'John Kendrew solves myoglobin by X-ray crystallography (Nobel 1962). A tangle, not a tidy shape: nobody expected that.'},
 {y:1961,t:'Anfinsen: sequence encodes fold',d:'Christian Anfinsen shows that unfolded ribonuclease refolds on its own, so the sequence alone determines the structure (Nobel 1972). That is why prediction should be possible at all.'},
 {y:1969,t:'Levinthal paradox',d:'Cyrus Levinthal points out that a chain cannot find its fold by random search. Folding must follow guided pathways (scene 8).'},
 {y:1971,t:'Protein Data Bank founded',d:'The PDB starts with 7 structures. It now holds on the order of 200,000+ and is the training data for modern predictors.'},
 {y:1994,t:'CASP begins',d:'Critical Assessment of protein Structure Prediction: a biennial blind competition. Groups predict structures that experimentalists have solved but not yet published.'},
 {y:1998,t:'Rosetta',d:'David Baker\'s group develops Rosetta for structure prediction; in 2003 it is turned around to design a new protein (Top7).'},
 {y:2008,t:'Foldit',d:'A citizen-science puzzle game where players fold proteins; players\' solutions outperformed algorithms on some problems.'},
 {y:2018,t:'AlphaFold 1 (CASP13)',d:'DeepMind tops CASP13 by using deep learning to predict distances between residues from evolutionary data.'},
 {y:2020,t:'AlphaFold2 (CASP14)',d:'Median GDT_TS of 92.4: for many targets, accuracy comparable to experiment. Widely described as solving the single-chain "structure prediction problem".'},
 {y:2021,t:'AlphaFold DB & RoseTTAFold',d:'Methods and code published (Jumper et al., Nature 2021; Baek et al., Science 2021). AlphaFold DB opens with predictions for the human proteome.'},
 {y:2022,t:'200 million structures',d:'AlphaFold DB (EMBL-EBI + DeepMind) expands to over 200 million predicted structures, covering most known protein sequences.'},
 {y:2024,t:'AlphaFold 3 & the Nobel',d:'AlphaFold 3 predicts complexes with DNA, RNA and ligands. The 2024 Chemistry Nobel: Demis Hassabis and John Jumper (prediction) and David Baker (computational design).'}];
 const gi=w.querySelector('#gi');const st=mkStage(w,{pos:[0,6,26],target:[0,0,0],auto:0,minD:6,maxD:70,onPick:h=>{if(h)sel(h.object.userData.i)}});if(!st)return;addStars(st,200,110);
 const X=i=>i*5.5-30;const spheres=M.map((m,i)=>{const c=new T.Color().setHSL(.55+i/M.length*.4,.75,.58);const s=sphereM(1.1,c,{em:c,ei:.3});s.position.set(X(i),Math.sin(i*.8)*2,0);s.userData.i=i;st.add(s,true);const l=makeLabel(String(m.y),'#fde68a',1.2);l.position.set(X(i),s.position.y+2,0);st.scene.add(l);if(i)st.scene.add(lineM([X(i-1),Math.sin((i-1)*.8)*2,0],[X(i),s.position.y,0],0x4a6fb5,.8));return s});
 let cur=0;function sel(i){cur=clamp(i,0,M.length-1);gi.innerHTML=infoBox(M[cur].y+': '+M[cur].t,M[cur].d);st.focus([X(cur),spheres[cur].position.y,0],18,.6);react(M[cur].t,'think')}
 w.querySelector('#tp').onclick=()=>sel(cur-1);w.querySelector('#tn').onclick=()=>sel(cur+1);st.up.push((dt,t)=>spheres.forEach((s,i)=>s.scale.setScalar(i===cur?1.3+.1*Math.sin(t*4):1)));sel(0)}});

/* ===== g12: how AlphaFold works ===== */
(function(){
SCENES.push({id:'g12',belt:2,mood:'think',title:'How AlphaFold Works (Conceptually)',
html:`<p class="lead">Three views: <b>co-evolution contacts</b> (the key clue), <b>prediction vs experiment</b> (it works), and <b>confidence</b> (it tells you where it doubts itself).</p>
<div class="grid"><div class="card"><div class="row" id="tb"></div>${mkCv()}</div><div class="card info"><div id="x2" style="margin-bottom:8px"></div><div id="gi"></div></div></div>`,
init(w){const gi=w.querySelector('#gi'),x2=w.querySelector('#x2');let st=null,tab='co';
 function co(){const S=STRUCT['1UBQ'];st=mkStage(w,{pos:[0,0,60],auto:.3,minD:5,maxD:150});if(!st)return;addStars(st,100,250);const pv=new ProteinView(st,S,{mode:'ss'});fitCamera(st,pv,3);st.up.push(()=>pv.update());const P=caList(S,'A'),n=P.length;
  const D=P.map(a=>P.map(b=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])));
  x2.innerHTML=`<div class="row"><canvas id="cm" width="${n*4}" height="${n*4}" style="width:min(100%,${n*4}px);image-rendering:pixelated;border:1px solid #2a4a8c;cursor:crosshair;background:#050a22"></canvas><div class="mini" id="cmi" style="flex:1;min-width:150px">Click the contact map: a dot at (i, j) means residues i and j are within 8 Å in 3D, even if far apart in sequence.</div></div>`;
  const cm=x2.querySelector('#cm'),cx=cm.getContext('2d');let sel=null;const draw=()=>{cx.clearRect(0,0,n*4,n*4);for(let i=0;i<n;i++)for(let j=0;j<n;j++){if(D[i][j]<8){const far=Math.abs(i-j)>5;cx.fillStyle=far?'#22d3ee':'#2a4a8c';cx.fillRect(i*4,j*4,4,4)}}if(sel){cx.strokeStyle='#fde047';cx.lineWidth=1;cx.strokeRect(sel[0]*4,sel[1]*4,4,4)}};draw();
  const mk=[0,1].map(()=>{const s=sphereM(1.6,'#fde047',{em:'#fde047',ei:.6,op:.9});s.visible=false;st.scene.add(s);return s});let ln=null;
  cm.onclick=e=>{const r=cm.getBoundingClientRect(),i=Math.floor((e.clientX-r.left)/r.width*n),j=Math.floor((e.clientY-r.top)/r.height*n);sel=[i,j];draw();mk[0].position.set(...P[i]);mk[1].position.set(...P[j]);mk.forEach(m=>m.visible=true);if(ln)st.scene.remove(ln);ln=lineM(P[i],P[j],0xfde047,1);st.scene.add(ln);
   x2.querySelector('#cmi').innerHTML=`Residues <b>${i+1}</b> and <b>${j+1}</b>: ${D[i][j].toFixed(1)} Å apart in 3D, ${Math.abs(i-j)} apart in sequence. ${D[i][j]<8&&Math.abs(i-j)>5?'<span class="ok">A long-range contact: exactly what co-evolution can reveal.</span>':D[i][j]<8?'A local contact.':'Not in contact.'}`;react('Contact '+(i+1)+'–'+(j+1),'think')};
  gi.innerHTML=infoBox('Clue 1: positions that mutate together touch',`Across thousands of related proteins (a multiple sequence alignment, MSA), if residue <i>i</i> becomes bigger whenever residue <i>j</i> becomes smaller, they probably sit next to each other and must stay compatible. <br><b>Toy example (made-up sequences)</b>:<pre class="cheat" style="max-height:none;font-size:12px">seq1  …<span style="color:#fbbf24">G</span>……<span style="color:#f87171">W</span>…
seq2  …<span style="color:#fbbf24">A</span>……<span style="color:#f87171">F</span>…
seq3  …<span style="color:#fbbf24">S</span>……<span style="color:#f87171">Y</span>…
seq4  …<span style="color:#fbbf24">G</span>……<span style="color:#f87171">W</span>…</pre>AlphaFold2 feeds the MSA into a neural network (the "Evoformer") that refines a pairwise map of how residues relate, then a "structure module" turns it into 3D coordinates, and the whole thing recycles its own output a few times. AlphaFold 3 uses a diffusion approach to also place ligands, DNA and RNA. Shown: ubiquitin (1UBQ).`)}
 function exp(){const E=STRUCT['2HHB'],AFS=STRUCT['AF-P68871'];st=mkStage(w,{pos:[0,0,60],auto:.4,minD:5,maxD:150});if(!st)return;addStars(st,100,250);
  const eB=caList(E,'B'),aB=caList(AFS,'A').slice(1);const n=Math.min(eB.length,aB.length);const f=superpose(eB.slice(0,n),aB.slice(0,n));const AFt=transformStruct(AFS,f);
  const pvE=new ProteinView(st,{ch:{B:E.ch.B},het:[]},{mode:'chain',lod:false});const pvA=new ProteinView(st,AFt,{mode:'plddt',lod:false});fitCamera(st,pvE,3);
  const r=rmsd(eB.slice(0,n),aB.slice(0,n).map(f));let showE=true,showA=true;
  const upd=()=>{pvE.group.visible=showE;pvA.group.visible=showA};
  x2.innerHTML=`<div class="row"><button class="chip on" id="bE">Experiment (white/cyan: PDB 2HHB chain β)</button><button class="chip on" id="bA">AlphaFold prediction (colored by pLDDT)</button></div>`;
  x2.querySelector('#bE').onclick=e=>{showE=!showE;e.currentTarget.classList.toggle('on',showE);upd()};x2.querySelector('#bA').onclick=e=>{showA=!showA;e.currentTarget.classList.toggle('on',showA);upd()};
  const tm=pvA.chains[0].res.map(r=>r.b);const avg=tm.reduce((a,b)=>a+b,0)/tm.length;
  gi.innerHTML=infoBox('Prediction vs experiment: human hemoglobin β',`The AlphaFold model (AF-P68871) was superimposed on the experimental structure. Backbone (Cα) RMSD over ${n} residues: <b>${r.toFixed(2)} Å</b>. Atoms are ≈ 1.5 Å apart in a bond, so this is close to atomic agreement. Mean pLDDT = <b>${avg.toFixed(0)}</b>.<p class="mini">This protein is in the training data's neighbourhood: hemoglobin is among the best-studied proteins. Accuracy is lower for rare or unusual proteins. Toggle each layer to compare.</p>`);upd()}
 function conf(){const P=STRUCT['AF-P04637'],Q=STRUCT['AF-P37840'];st=mkStage(w,{pos:[0,0,150],auto:.3,minD:5,maxD:400});if(!st)return;addStars(st,100,500);
  const pvs={p53:new ProteinView(st,P,{mode:'plddt',lod:false}),syn:new ProteinView(st,Q,{mode:'plddt',lod:false})};let cur='p53';const stats=k=>{const b=pvs[k].chains[0].res.map(r=>r.b),n=b.length,c=t=>b.filter(t).length/n*100;return{vh:c(x=>x>90),hi:c(x=>x>70&&x<=90),lo:c(x=>x>50&&x<=70),vl:c(x=>x<=50),n}};
  const show=k=>{cur=k;for(const q in pvs)pvs[q].group.visible=q===k;fitCamera(st,pvs[k],2.6);const s=stats(k);x2.querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',b.dataset.k===k));
   gi.innerHTML=infoBox(k==='p53'?'Human p53 (AF-P04637, 393 residues)':'α-synuclein (AF-P37840, 140 residues)',`Colored by <b>pLDDT</b> (per-residue confidence, 0–100):<br><span style="color:#0053d6">■</span> &gt;90 very high · <span style="color:#65cbf3">■</span> 70–90 confident · <span style="color:#ffdb13">■</span> 50–70 low · <span style="color:#ff7d45">■</span> &lt;50 very low.<div class="bar" style="margin:6px 0"><i style="width:${s.vh+s.hi}%"></i></div><b>${(s.vh+s.hi).toFixed(0)}%</b> of residues are confident (&gt;70), <b>${s.vl.toFixed(0)}%</b> very low.<p>${k==='p53'?'p53 is a tumour suppressor. A folded DNA-binding core (blue) is flanked by long floppy regions (orange). Those are <b>intrinsically disordered</b>: they have no single fixed structure, so there is nothing for AlphaFold to get "right". Low pLDDT usually flags disorder rather than a failed prediction.':'α-synuclein (linked to Parkinson\'s) is largely disordered in solution. AlphaFold shows a low-confidence helix-like model; it can adopt different shapes depending on its partners (e.g. membranes), which a single static prediction cannot represent.'}</p>`)};
  x2.innerHTML=`<div class="row"><button class="chip" data-k="p53">p53</button><button class="chip" data-k="syn">α-synuclein</button></div>`;x2.querySelectorAll('.chip').forEach(b=>b.onclick=()=>show(b.dataset.k));show('p53')}
 function showTab(t){tab=t;if(st){st.destroy();st=null}freshCanvas(w);x2.innerHTML='';w.querySelectorAll('#tb .chip').forEach(b=>b.classList.toggle('on',b.dataset.k===t));({co,exp,conf})[t]()}
 [['co','1 · Contacts'],['exp','2 · Prediction vs experiment'],['conf','3 · Confidence (pLDDT)']].forEach(([k,n])=>{const b=el('button','chip',n);b.dataset.k=k;b.onclick=()=>showTab(k);w.querySelector('#tb').append(b)});showTab('co')}});
})();

/* ===== g13: design & drugs ===== */
SCENES.push({id:'g13',belt:2,mood:'happy',title:'Design & Drugs',
html:`<p class="lead"><b>Drugs</b>: fit a molecule into a protein's pocket. <b>Design</b>: write a sequence for a shape that nature never made.</p>
<div class="grid"><div class="card"><div class="row" id="tb"></div><div id="x2" style="margin:6px 0"></div>${mkCv()}</div><div class="card info" id="gi"></div></div>`,
init(w){const gi=w.querySelector('#gi'),x2=w.querySelector('#x2');let st=null;
 function drug(){const S=STRUCT['1HSG'];st=mkStage(w,{pos:[0,0,70],auto:.3,minD:4,maxD:180});if(!st)return;addStars(st,100,300);const pv=new ProteinView(st,S,{chains:['A','B'],mode:'chain',lod:false});fitCamera(st,pv,2.4);
  pv.chains.forEach(c=>{c.mesh.material.transparent=true;c.mesh.material.opacity=.45});const lig=S.het.find(h=>h[0]==='MK1');const la=lig[3];const lc=la.reduce((a,p)=>[a[0]+p[1]/la.length,a[1]+p[2]/la.length,a[2]+p[3]/la.length],[0,0,0]);const hs=pv.hetBy[lig[1]];
  const dir=new T.Vector3(lc[0]-pv.center[0],lc[1]-pv.center[1],lc[2]-pv.center[2]);if(dir.length()<3)dir.set(1,0,0);dir.normalize();
  const heavy=pv.chains.flatMap(c=>c.res.map((r,i)=>({c,i,r}))).filter(o=>o.r.atoms.some(a=>a[0]==='CA'));
  const contacts=off=>{const set=new Set();let pairs=0;for(const o of heavy){for(const a of o.r.atoms){for(const l of la){const dx=a[1]-(l[1]+dir.x*off),dy=a[2]-(l[2]+dir.y*off),dz=a[3]-(l[3]+dir.z*off);if(dx*dx+dy*dy+dz*dz<16){pairs++;set.add(o.c.id+o.r.n)}}}}return{res:set.size,pairs}};
  const upd=off=>{hs.g.position.set(dir.x*off,dir.y*off,dir.z*off);const c=contacts(off);x2.querySelector('#ct').innerHTML=`Atom pairs within 4 Å: <b>${c.pairs}</b> · protein residues touching the drug: <b>${c.res}</b>`;};
  x2.innerHTML=`<label for="ps">Pull the drug out: <b id="pv">0</b> Å</label><input id="ps" type="range" min="0" max="40" value="0"><p id="ct" class="mini"></p>`;x2.querySelector('#ps').oninput=e=>{x2.querySelector('#pv').textContent=e.target.value;upd(+e.target.value)};
  pv.hetOn=true;pv.syncHet();upd(0);st.focus(lc,48,.8);
  gi.innerHTML=infoBox('HIV-1 protease + indinavir (PDB 1HSG)',`HIV protease is a two-chain enzyme (blue/pink) that cuts viral polyproteins; blocking it stops the virus maturing. The green sticks are <b>indinavir</b>, one of the first drugs designed using a 3D structure (approved 1996). Drag the slider to withdraw the molecule and watch the contacts vanish.<p class="mini">Modern pipelines use predicted structures too, to find pockets, dock millions of candidate molecules, and then test the best in the lab.</p>`)}
 function design(){const S=STRUCT['1QYS'];st=mkStage(w,{pos:[0,0,60],auto:.5,minD:4,maxD:150});if(!st)return;addStars(st,100,250);const pv=new ProteinView(st,S,{mode:'ss'});fitCamera(st,pv,2.6);st.up.push(()=>pv.update());
  x2.innerHTML=`<div class="mini">Designed sequence:</div><div style="font-family:ui-monospace,Menlo,monospace;font-size:12px;word-break:break-all">${seqOf(S,'A')}</div><div class="row"><button class="chip" data-m="ss">Secondary structure</button><button class="chip" data-m="hydro">Hydropathy</button><button class="chip" data-m="rainbow">N→C rainbow</button></div>`;x2.querySelectorAll('.chip').forEach(b=>b.onclick=()=>pv.setMode(b.dataset.m));
  st.onPick=h=>{const s=pv.resOf(h);if(s)pv.select(s)};
  gi.innerHTML=infoBox('Top7: a protein that never existed (PDB 1QYS)',`In 2003, Baker's lab designed <b>Top7</b>: a 92-residue protein with a fold not found in nature. The design started from a target shape, searched for an amino-acid sequence that would fit it (Rosetta), and the experimental structure matched the design to about 1.2 Å. <p><b>The design loop:</b> 1 choose a target shape or function → 2 compute sequences that favour it → 3 predict their structures (AlphaFold-like checks) → 4 make the best ones in the lab → 5 measure and repeat.</p><p>Since then, AI-based methods (RFdiffusion, ProteinMPNN) design binders, enzymes and nanoparticle vaccine scaffolds; a COVID-19 vaccine built on a designed protein nanoparticle was approved in South Korea in 2022. <b>2024 Chemistry Nobel</b>: David Baker (computational protein design) shared the prize with Demis Hassabis and John Jumper (AlphaFold).</p>`)}
 function show(t){if(st){st.destroy();st=null}freshCanvas(w);w.querySelectorAll('#tb .chip').forEach(b=>b.classList.toggle('on',b.dataset.k===t));t==='drug'?drug():design()}
 [['drug','Drug in a pocket'],['design','De novo design (Top7)']].forEach(([k,n])=>{const b=el('button','chip',n);b.dataset.k=k;b.onclick=()=>show(k);w.querySelector('#tb').append(b)});show('drug')}});

/* ===== g14: open problems ===== */
(function(){
const OP=[{id:'dyn',n:'Dynamics',col:'#facc15',st:'partial',pos:[-14,6,0],who:'Drug designers, enzymologists',why:'Proteins flex, breathe and switch states, and function often depends on motion. Predictors give one static snapshot. Simulations (molecular dynamics) reach microseconds to milliseconds with huge compute, but biology happens over milliseconds to hours.',status:'Partial: cryo-EM can sort conformations; AI methods are starting to sample ensembles. Try the demo: hemoglobin changes shape when it binds oxygen.',ex:'dyn'},
 {id:'idp',n:'Disordered proteins',col:'#f87171',st:'open',pos:[-9,-6,5],who:'Cancer and neuro-degeneration researchers',why:'A large fraction of human proteins (often estimated at ~30% or more) have long disordered regions with no single structure. They act through flexibility, binding many partners and forming condensates.',status:'Open: low pLDDT flags them, but describing their ensembles and functions is hard.',ex:'idp'},
 {id:'path',n:'Folding pathways',col:'#f87171',st:'open',pos:[-3,8,-4],who:'Biophysicists, misfolding-disease researchers',why:'Predictors output the final fold, not the route or the speed. Real folding starts while the chain is still being made by the ribosome and is helped by chaperones.',status:'Open: how, how fast, and why some proteins misfold remain active research.',ex:null},
 {id:'cx',n:'Complexes',col:'#facc15',st:'partial',pos:[4,-4,6],who:'Systems and structural biologists',why:'Cells run on assemblies of many proteins, nucleic acids and ligands. Predicting who binds whom, how tightly, and the full architecture is much harder than single chains; antibody–antigen docking is notoriously tough.',status:'Partial: AlphaFold-Multimer and AlphaFold 3 predict many complexes; confidence and coverage lag behind single chains.',ex:null},
 {id:'mem',n:'Membrane proteins',col:'#facc15',st:'partial',pos:[10,6,0],who:'Pharma (GPCRs, channels, transporters are common drug targets)',why:'They live in lipid bilayers, are hard to purify and crystallize, and depend on their lipid environment and on being embedded in the right orientation.',status:'Improving: cryo-EM boom plus predictions; lipids and dynamics remain tricky. Demo: bacteriorhodopsin (hydrophobic outside).',ex:'mem'},
 {id:'var',n:'Mutation effects',col:'#facc15',st:'partial',pos:[15,-5,-4],who:'Clinical geneticists',why:'Given a variant, does it destabilize the fold, break a binding site or do nothing? Every person has thousands of rare variants. Experiments (deep mutational scans) cover only a fraction.',status:'Partial: tools such as AlphaMissense (2023) score every possible human missense variant, but accuracy is limited and mechanism is usually unknown.',ex:null},
 {id:'fn',n:'Function from structure',col:'#f87171',st:'open',pos:[-2,-10,-1],who:'Everyone using AlphaFold DB',why:'A shape does not tell you what a protein does. Hundreds of millions of predicted structures have no functional annotation; identifying active sites, partners and regulation remains slow.',status:'Open: active research mixing structure search, language models and experiments.',ex:null},
 {id:'enz',n:'Designing enzymes',col:'#facc15',st:'frontier',pos:[18,2,6],who:'Green chemistry, therapeutics',why:'Designing a binder is now routine; designing efficient catalysts needs sub-ångström precision and motions that match the reaction.',status:'Frontier: some designed enzymes work, usually needing lab evolution to reach natural-like speeds.',ex:null}];
SCENES.push({id:'g14',belt:2,mood:'alert',title:'Open Problems: What Nobody Can Do Yet',
html:`<p class="lead">Click a node: <span style="color:#f87171">● open</span> · <span style="color:#facc15">● partial / frontier</span>. Three have a live 3D demo.</p>
<div class="grid"><div class="card"><div class="row" id="tb"></div><div id="x2" style="margin:6px 0"></div>${mkCv()}</div><div class="card info" id="gi"><h3>Pick a frontier</h3><p>AlphaFold made one thing routine: a good static structure for most single, folded proteins. Almost everything else about proteins is still a research problem.</p></div></div>`,
init(w){const gi=w.querySelector('#gi'),x2=w.querySelector('#x2');let st=null,tab='map';
 const describe=n=>{gi.innerHTML=infoBox(n.n+' — '+n.st,`<b>Who cares:</b> ${n.who}<br><b>Why it is hard:</b> ${n.why}<br><b>Status:</b> ${n.status}`,n.ex?`<button class="btn" id="dm">Show 3D demo ▶</button>`:'');const b=gi.querySelector('#dm');if(b)b.onclick=()=>showTab(n.ex)};
 function map(){const r=nodeGraph(w,OP.map(o=>({id:o.id,label:o.n,pos:o.pos,color:o.col,r:1.7})),[['dyn','idp'],['idp','path'],['path','cx'],['cx','mem'],['mem','var'],['var','enz'],['fn','cx'],['fn','idp'],['dyn','path'],['cx','enz']],{pos:[2,6,50],focus:24},n=>describe(OP.find(o=>o.id===n.id)));st=r&&r.st;x2.innerHTML='<div class="mini">Drag to orbit · click a node</div>'}
 function dyn(){const A=STRUCT['2HHB'],B=STRUCT['1HHO'];st=mkStage(w,{pos:[0,0,60],auto:.3,minD:5,maxD:150});if(!st)return;addStars(st,100,250);
  const cat=S=>['A','B'].flatMap(c=>caList(S,c));const ref=cat(A),mov=cat(B);const f=superpose(ref,mov);const mv=mov.map(f);const R=rmsd(ref,mv);
  const pv=new ProteinView(st,{ch:{A:A.ch.A,B:A.ch.B},het:[]},{chains:['A','B'],mode:'chain',lod:false});fitCamera(st,pv,2.6);let off=0;const idx={A:0,B:A.ch.A.filter(r=>r[4].some(a=>a[0]==='CA')).length};
  const set=t=>{for(const c of pv.chains){const o=idx[c.id];c.cur=c.nat.map((p,i)=>{const q=mv[o+i];return[lerp(p[0],q[0],t),lerp(p[1],q[1],t),lerp(p[2],q[2],t)]})}pv.rebuild()};
  x2.innerHTML=`<label for="dm">Deoxy (2HHB) ↔ oxy (1HHO): <b id="dv">0%</b></label><input id="dm" type="range" min="0" max="100" value="0"><div class="mini">Cα RMSD after superposing the α₁β₁ dimer: ${R.toFixed(1)} Å (1HHO contains one αβ pair; the full tetramer rotates more). Colors: chain.</div>`;x2.querySelector('#dm').oninput=e=>{x2.querySelector('#dv').textContent=e.target.value+'%';set(e.target.value/100)};
  gi.innerHTML=infoBox('Demo: a protein in motion','Hemoglobin switches between a tense (T, deoxy) and a relaxed (R, oxy) state; oxygen binding at one site shifts the subunits and makes the next oxygen bind more easily (cooperativity). One predicted structure cannot show this. Slide to morph between two experimental structures (linear interpolation, so intermediate shapes are only illustrative).')}
 function idp(){const P=STRUCT['AF-P04637'];st=mkStage(w,{pos:[0,0,150],auto:.3,minD:5,maxD:400});if(!st)return;addStars(st,100,500);const pv=new ProteinView(st,P,{mode:'plddt',lod:false});fitCamera(st,pv,2.6);x2.innerHTML='<div class="mini">Same AlphaFold model of p53 as before. Orange/yellow = very low/low confidence, mostly disordered tails.</div>';
  gi.innerHTML=infoBox('Demo: disorder','The blue core is a stable domain that binds DNA. The orange strands are not wrongly predicted so much as undefined: in a cell they wriggle through many shapes and bind partners, including other proteins and modifications. Predicting an <i>ensemble</i> and its function is open.')}
 function mem(){const S=STRUCT['1C3W'];st=mkStage(w,{pos:[0,0,60],auto:.4,minD:5,maxD:150});if(!st)return;addStars(st,100,250);const pv=new ProteinView(st,S,{mode:'hydro',lod:false});fitCamera(st,pv,2.6);st.up.push(()=>pv.update());
  x2.innerHTML='<div class="row"><button class="chip on" data-m="hydro">Hydropathy</button><button class="chip" data-m="ss">Secondary structure</button><button class="chip" data-m="rainbow">N→C</button></div>';x2.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{pv.setMode(b.dataset.m);x2.querySelectorAll('.chip').forEach(x=>x.classList.toggle('on',x===b))});
  gi.innerHTML=infoBox('Demo: bacteriorhodopsin (PDB 1C3W)','A bundle of seven helices that spans a membrane (like GPCRs, which are targets of a large share of drugs). Orange = water-fearing: the outside surface faces the lipid tails, the opposite of a soluble protein where the hydrophobic residues hide inside. This pattern helps predictors but lipids, orientation and motion remain difficult.')}
 function showTab(t){tab=t;if(st){st.destroy();st=null}freshCanvas(w);x2.innerHTML='';w.querySelectorAll('#tb .chip').forEach(b=>b.classList.toggle('on',b.dataset.k===t));({map,dyn,idp,mem})[t]()}
 [['map','Frontier map'],['dyn','Demo: dynamics'],['idp','Demo: disorder'],['mem','Demo: membrane']].forEach(([k,n])=>{const b=el('button','chip',n);b.dataset.k=k;b.onclick=()=>showTab(k);w.querySelector('#tb').append(b)});showTab('map')}});
})();

/* ===== g15: quiz + cheat sheet + resources ===== */
SCENES.push({id:'g15',belt:2,mood:'happy',title:'Final Quiz, Cheat Sheet & Where to Explore',
html:`<p class="lead">Score at least 6 / 8 to reach <b>Frontier</b> rank.</p><div class="grid"><div class="card" id="qz"></div><div class="card info"><h3>Cheat sheet</h3><pre class="cheat" id="ch"></pre><div class="row"><button class="btn" id="cp">📋 Copy</button><span class="mini" id="cm"></span></div></div></div>
<div class="grid" style="margin-top:12px"><div class="card info"><h3>Explore the real data</h3><p><a target="_blank" rel="noopener" href="https://www.rcsb.org" style="color:#22d3ee">RCSB Protein Data Bank</a>, experimental structures (all structures here come from it) · <a target="_blank" rel="noopener" href="https://alphafold.ebi.ac.uk" style="color:#22d3ee">AlphaFold DB</a> · <a target="_blank" rel="noopener" href="https://www.uniprot.org" style="color:#22d3ee">UniProt</a> · <a target="_blank" rel="noopener" href="https://gnomad.broadinstitute.org" style="color:#22d3ee">gnomAD</a> (human variation) · <a target="_blank" rel="noopener" href="https://genome.ucsc.edu" style="color:#22d3ee">UCSC Genome Browser</a> · <a target="_blank" rel="noopener" href="https://www.ncbi.nlm.nih.gov/clinvar/" style="color:#22d3ee">ClinVar</a> · <a target="_blank" rel="noopener" href="https://fold.it" style="color:#22d3ee">Foldit</a></p></div>
<div class="card info"><h3>Sources &amp; caveats</h3><p class="mini">Nurk et al., <i>Science</i> 2022 (T2T-CHM13) · Liao et al., <i>Nature</i> 2023 (pangenome) · 1000 Genomes Consortium, <i>Nature</i> 2015 · ENCODE, <i>Nature</i> 2012 and Graur et al. 2013 (function debate) · Jumper et al., <i>Nature</i> 2021 (AlphaFold2) · Abramson et al., <i>Nature</i> 2024 (AlphaFold 3) · Kuhlman et al., <i>Science</i> 2003 (Top7) · Kyte &amp; Doolittle 1982; Zamyatnin 1972 (scales) · Levinthal 1969; Anfinsen 1973. Numbers marked ≈ are approximate, vary by annotation or definition, and some history values are rounded. Gene counts per chromosome vary by release. Demos are simplified cartoons.</p></div></div>`,
init(w){const CH=`GENOMES & PROTEINS CHEAT SHEET
• Genome ≈ 3.1 Gb per haploid set (T2T-CHM13: 3.055 Gb). ~20,000 protein-coding genes; ~1.5% of DNA codes for protein; ~50% repeat-derived (LINE-1 ~17%, Alu ~10%).
• "Function" depends on definition: ~80% biochemically active (ENCODE) vs <10% under evolutionary constraint.
• Two people differ at ~0.1% of letters; a genome has ~4–5 M variant sites and ~2,500 structural variants. Non-Africans carry ~1–2% Neanderthal DNA.
• Regulation: enhancers loop to promoters; methylation tends to silence; same genome, different expression.
• Proteins: 20 amino acids; hydrophobicity (hydrophobic effect) drives folding into a buried core.
• Structure levels: primary (sequence) → secondary (α/β) → tertiary (3D fold) → quaternary (assembly).
• Levinthal paradox: random search is impossible; real folding follows an energy funnel.
• Misfolding: sickle cell (β6 Glu→Val sticky patch); amyloid = cross-β fibrils (Alzheimer's, Parkinson's, prions).
• AlphaFold: co-evolution in an MSA → structure; pLDDT gives per-residue confidence (<50 often disordered). CASP14 median GDT 92.4; AlphaFold DB >200 M structures.
• Design: Top7 (2003); 2024 Chemistry Nobel to Baker (design), Hassabis & Jumper (AlphaFold).
• Open: dynamics, disorder, folding pathways, complexes, membrane proteins, mutation effects, function, enzyme design.`;
 w.querySelector('#ch').textContent=CH;w.querySelector('#cp').onclick=()=>{const done=()=>w.querySelector('#cm').textContent='Copied!';if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(CH).then(done,()=>w.querySelector('#cm').textContent='Select the text and copy it.');else{const r=document.createRange();r.selectNodeContents(w.querySelector('#ch'));getSelection().removeAllRanges();getSelection().addRange(r);w.querySelector('#cm').textContent='Selected: copy with Ctrl/Cmd+C'}};
 const Q=[{q:'What fraction of the human genome codes for protein?',o:['≈ 50%','≈ 15%','≈ 1.5%','≈ 0.01%'],a:2,e:'Only about 1–2% is protein-coding exons.'},
 {q:'What is the core disagreement behind the ENCODE "80% functional" claim?',o:['The genome was mis-sequenced','Biochemical activity is not the same as selected, evolutionarily meaningful function','Only 20% of cells were tested','Repeats are always functional'],a:1,e:'Activity ≠ function; conservation suggests < 10% is under strong selection.'},
 {q:'About what fraction of letters differ between two unrelated people?',o:['≈ 0.1%','≈ 1%','≈ 10%','≈ 0.0001%'],a:0,e:'≈ 1 in 1,000, i.e. millions of sites.'},
 {q:'What does an enhancer–promoter loop do?',o:['Copies the gene','Brings a distant regulatory element next to the gene to activate it','Folds the protein','Deletes introns'],a:1,e:'DNA looping makes distant enhancers physically touch promoters.'},
 {q:'Which property most drives a soluble protein to collapse into a compact core?',o:['Color of side chains','The hydrophobic effect','Gene length','Codon usage'],a:1,e:'Water-fearing residues hide from water inside the core.'},
 {q:'What does the Levinthal paradox say?',o:['Proteins never fold','Random search for the fold is impossibly slow, so folding must be guided (funnel-like)','Proteins fold only in cells','All proteins have one fold'],a:1,e:'Hence the energy-funnel picture.'},
 {q:'A residue with pLDDT below 50 most often means…',o:['Very confident prediction','Low confidence, often a disordered region','A mutated residue','A membrane residue'],a:1,e:'Low pLDDT often flags intrinsic disorder.'},
 {q:'Which is still an open problem even after AlphaFold?',o:['A decent static structure of most folded single chains','Predicting full conformational ensembles and folding pathways','Finding any protein sequence','Sequencing a genome'],a:1,e:'Dynamics, ensembles and pathways remain hard.'}];
 quiz(w.querySelector('#qz'),Q,sc=>{const box=w.querySelector('#qz');const pass=sc>=6;box.innerHTML=`<p class="big">${sc} / ${Q.length}</p><p>${pass?'🏆 <b>Frontier</b> rank unlocked!':'Close. Review the scenes and try again: you need 6.'}</p>`;const b=el('button','btn',pass?'Replay quiz':'Try again');b.onclick=()=>go(14);box.append(b);
  if(pass){maxRank=3;setRankUI(3);toast('🏆 Rank: Frontier!');bow();react('Frontier rank unlocked!','happy')}else react('Review and try again.','think')})}});
