/* ===== Genomes & Proteins: Part B (proteins) ===== */
const gauss=()=>{let u=0,v=0;while(!u)u=Math.random();v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)};
/* ===== g6: amino acids property space ===== */
SCENES.push({id:'g6',belt:1,mood:'think',title:'Twenty Building Blocks',
html:`<p class="lead">Each sphere is an amino acid. <b>Left–right</b> = hydropathy (right is water-fearing), <b>up</b> = side-chain volume, sphere size = volume. Click to see it, and click several to build a peptide and compute its average hydropathy.</p>
<div class="grid"><div class="card"><div class="row" id="cm"></div>${mkCv()}<div class="hint">Drag to rotate · scroll to zoom</div></div><div class="card info" id="gi"><h3>Click an amino acid</h3><p>Proteins are chains of these twenty. Side chains differ in size, charge and how they interact with water.</p>
<div class="mini" style="margin-top:8px">Peptide builder</div><div id="pp" class="seq" style="min-height:34px"></div><p id="pm" class="mini"></p><button class="btn sec" id="pc">Clear</button></div></div>`,
init(w){const aas=Object.keys(KD),gi=w.querySelector('#gi');let pep='',mode='group',selA=null;const st=mkStage(w,{pos:[0,3,30],target:[0,6,0],auto:.35,minD:8,maxD:80,onPick:h=>{if(h)pick(h.object.userData.a)}});if(!st)return;addStars(st,200,90);
 const zs={hydrophobic:-6,special:-2,polar:2,positive:6,negative:10};const M={};
 aas.forEach(a=>{const r=Math.cbrt(VOL[a])/Math.cbrt(100)*.9;const m=sphereM(r,GCOL[GROUP[a]],{em:GCOL[GROUP[a]],ei:.15});m.position.set(KD[a]*2.2,(VOL[a]-60)/170*14,zs[GROUP[a]]*.7+((a.charCodeAt(0)%3)-1)*.5);m.userData.a=a;st.add(m,true);M[a]=m;const l=makeLabel(a,'#04061a',1.2);l.position.copy(m.position);st.scene.add(l)});
 [['← water-loving',-12,-2],['water-fearing →',12,-2]].forEach(([t,x,y])=>{const l=makeLabel(t,'#9db3d8',1);l.position.set(x,y-1.5,-4);st.scene.add(l)});const lv=makeLabel('volume ↑','#9db3d8',1);lv.position.set(-13,7,-4);st.scene.add(lv);
 st.scene.add(lineM([-11,-1,-4],[11,-1,-4],0x4a6fb5,.6));st.scene.add(lineM([-11,-1,-4],[-11,14,-4],0x4a6fb5,.6));
 function pick(a){selA=a;const cod=[];for(const x of'TCAG')for(const y of'TCAG')for(const z of'TCAG')if(codon2aa(x+y+z)===a)cod.push(x+y+z);gi.querySelector('h3').textContent=AAFULL[a]+' ('+AN3(a)+', '+a+')';gi.querySelector('p').innerHTML=`<b>${GROUP[a]}</b> · hydropathy ${KD[a]>0?'+':''}${KD[a]} · volume ${VOL[a]} Å³<br>Codons: ${cod.join(', ')} (${cod.length})`;pep+=a;if(pep.length>30)pep=pep.slice(-30);pp()}
 const AN3=a=>AAN[a];
 function pp(){w.querySelector('#pp').innerHTML=[...pep].map(a=>`<span class="b" style="background:${GCOL[GROUP[a]]}">${a}</span>`).join('');const g=pep.length?[...pep].reduce((s,a)=>s+KD[a],0)/pep.length:0;w.querySelector('#pm').textContent=pep.length?`${pep.length} residues · mean hydropathy (GRAVY) = ${g.toFixed(2)} → ${g>1.2?'very hydrophobic: likely buried in a core or in a membrane':g<-1.2?'very hydrophilic: likely exposed to water':'mixed'}`:''}
 w.querySelector('#pc').onclick=()=>{pep='';pp()};
 [['group','Color by chemistry'],['kd','Color by hydropathy']].forEach(([k,n])=>{const b=el('button','chip'+(k===mode?' on':''),n);b.onclick=()=>{mode=k;w.querySelectorAll('#cm .chip').forEach(x=>x.classList.toggle('on',x===b));aas.forEach(a=>{const c=k==='group'?new T.Color(GCOL[GROUP[a]]):kdColor(KD[a]);M[a].material.color.copy(c);M[a].material.emissive.copy(c)})};w.querySelector('#cm').append(b)});
 [['hydrophobic','Hydrophobic'],['polar','Polar'],['positive','+ charged'],['negative','− charged'],['special','Special (G, P, C)']].forEach(([g,n])=>{const s=el('span','mini',`<span style="color:${GCOL[g]}">●</span> ${n}&nbsp; `);w.querySelector('#cm').append(s)});
 st.up.push((dt,t)=>{aas.forEach(a=>M[a].scale.setScalar(selA===a?1.18+.05*Math.sin(t*5):1))})}});

/* ===== g7: levels of structure ===== */
(function(){
const LV=[['1 · Primary: sequence','A linear chain of amino acids, read N→C. This is exactly what the gene specifies. Drag the slider to fold it.',0,'aa',['B']],
 ['2 · Secondary: helices & strands','Local shapes held by hydrogen bonds between backbone atoms: <b style="color:#f472b6">α-helices</b> and <b style="color:#fbbf24">β-strands</b>, joined by <b style="color:#7dd3fc">loops</b>. Hemoglobin is almost all helix.',1,'ss',['B']],
 ['3 · Tertiary: the 3D fold','The whole chain folds into a compact shape. Water-fearing residues (orange) bury inside; water-loving ones (blue) face out. The heme (sticks) holds the iron that binds O₂. Zoom in to see atoms.',1,'hydro',['B']],
 ['4 · Quaternary: assembly','Hemoglobin is a tetramer: two α and two β chains, each with a heme. Subunits move relative to each other when oxygen binds (see scene 14).',1,'chain',['A','B','C','D']]];
SCENES.push({id:'g7',belt:1,mood:'think',title:'Four Levels of Structure',
html:`<p class="lead">Real human hemoglobin (PDB 2HHB). Pick a level, <b>fold</b> the chain with the slider, click residues, and <b>zoom in</b> (scroll) until atoms and bonds appear.</p>
<div class="grid"><div class="card"><div class="row" id="lv"></div><div class="row"><label for="fs">Fold</label><input id="fs" type="range" min="0" max="100" value="100" aria-label="Fold"></div>${mkCv()}<div class="hint">Colors: see the panel. Scroll in to see ball-and-stick atoms around the view centre. Right-drag to pan.</div></div>
<div class="card info" id="gi"></div></div>
<div class="card" style="margin-top:12px"><div class="mini">Sequence of the β chain (click a letter to locate it; amino acid 1 is Val):</div><div id="sq" style="font-family:ui-monospace,Menlo,monospace;font-size:13px;word-break:break-all;line-height:1.7"></div></div>`,
init(w){const S=STRUCT['2HHB'];const st=mkStage(w,{pos:[0,0,90],auto:.3,minD:5,maxD:260});if(!st)return;addStars(st,150,300);
 const pv=new ProteinView(st,S,{chains:['A','B','C','D'],mode:'ss'});fitCamera(st,pv,2.4);st.up.push(()=>pv.update());const gi=w.querySelector('#gi');let lv=0,fold=1;const sq=w.querySelector('#sq'),seq=seqOf(S,'B');
 sq.innerHTML=[...seq].map((a,i)=>`<span data-i="${i}" style="color:${GCOL[GROUP[a]||'special']};cursor:pointer">${a}</span>`).join('');
 const info=sel=>{gi.innerHTML=infoBox(LV[lv][0],LV[lv][1],(sel?`<p class="mini"><b>Selected:</b> chain ${sel.c.id==='A'||sel.c.id==='C'?'α':'β'}, residue ${sel.r.n} = ${AAFULL[sel.r.aa]} (${sel.r.aa}), ${({H:'helix',E:'strand',C:'loop'})[sel.r.ss]}, hydropathy ${KD[sel.r.aa]}</p>`:'')+`<div class="mini">${lv===0?'<span style="color:#fbbf24">●</span> hydrophobic <span style="color:#38bdf8">●</span> polar <span style="color:#6366f1">●</span> + <span style="color:#f87171">●</span> −':lv===1?'<span style="color:#f472b6">●</span> helix <span style="color:#fbbf24">●</span> strand <span style="color:#7dd3fc">●</span> loop':lv===2?'blue = hydrophilic, orange = hydrophobic':'chains colored differently'}</div>`)}
 function setLevel(i,keep){lv=i;pv.showChains(LV[i][4]);pv.setMode(LV[i][3]);if(!keep){fold=LV[i][2];w.querySelector('#fs').value=fold*100;pv.setFold(fold)}w.querySelectorAll('#lv .chip').forEach((b,k)=>b.classList.toggle('on',k===i));info(null);fitCamera(st,pv,i===3?2.2:2.8);if(i<3){const c=pv.chains.find(c=>c.id==='B');const m=c.nat.reduce((a,p)=>[a[0]+p[0],a[1]+p[1],a[2]+p[2]],[0,0,0]).map(v=>v/c.nat.length);st.ctl.target.set(...m);st.cam.position.set(m[0]+8,m[1]+8,m[2]+(i===0?95:44))}}
 LV.forEach((l,i)=>{const b=el('button','chip',l[0].split(':')[0]);b.title=l[0];b.onclick=()=>{setLevel(i);react(l[0].split(': ')[1]||l[0],'think')};w.querySelector('#lv').append(b)});
 w.querySelector('#fs').oninput=e=>{fold=e.target.value/100;pv.setFold(fold)};
 st.onPick=h=>{const s=pv.resOf(h);if(s){pv.select(s);info(s)}};
 sq.onclick=e=>{const i=e.target.dataset&&e.target.dataset.i;if(i==null)return;const c=pv.chains.find(c=>c.id==='B');const s={c,i:+i,r:c.res[+i]};if(fold<1)return;pv.select(s);info(s);const p=c.nat[+i];st.focus(p,16,.8)};
 setLevel(0)}});
})();

/* ===== g8: Levinthal + energy landscape ===== */
(function(){
const R=x=>x;
function h(mode,x,z){const r2=x*x+z*z,r=Math.sqrt(r2);if(mode==='golf')return 6-7*Math.exp(-r2/2.2);const base=.02*r2;if(mode==='funnel')return base;const A=.45*(.35+.65*Math.min(1,r/16));return base+A*(Math.sin(.9*x+1.3)*Math.sin(.8*z+.4)+.6*Math.sin(1.7*x+1.1*z)+.4*Math.cos(2.1*z-.7*x))+0}
function grad(mode,x,z){const e=.05;return[(h(mode,x+e,z)-h(mode,x-e,z))/(2*e),(h(mode,x,z+e)-h(mode,x,z-e))/(2*e)]}
function sim(mode,x,z,temp,render){let vx=0,vz=0,n=0;const path=[];for(;n<(render?1e9:6000);n++){const[gx,gz]=grad(mode,x,z);vx=vx*.96-gx*.05+temp*gauss()*.05;vz=vz*.96-gz*.05+temp*gauss()*.05;x+=vx;z+=vz;if(Math.abs(x)>19){x=Math.sign(x)*19;vx*=-.5}if(Math.abs(z)>19){z=Math.sign(z)*19;vz*=-.5}if(render)break}return{x,z,vx,vz,n}}
SCENES.push({id:'g8',belt:2,mood:'think',title:'Why Folding Is Hard: Levinthal & the Funnel',
html:`<p class="lead"><b>Part 1</b>: the paradox in numbers. <b>Part 2</b>: a 3D energy landscape. Click the surface to drop a ball (low = more stable), or drop 40 random balls and see how often each landscape finds the native state in the middle.</p>
<div class="card"><div class="row"><b>Levinthal calculator</b></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))"><div><label for="ln">Residues: <b id="lnv">100</b></label><input id="ln" type="range" min="10" max="300" value="100"></div><div><label for="ls">Shapes per residue: <b id="lsv">3</b></label><input id="ls" type="range" min="2" max="6" value="3"></div><div><label for="lr">Shapes tried per second: <b id="lrv">10^13</b></label><input id="lr" type="range" min="6" max="15" value="13"></div></div><p id="lo" class="big" style="font-size:18px"></p></div>
<div class="grid" style="margin-top:12px"><div class="card"><div class="row" id="lm"></div>${mkCv()}</div><div class="card info" id="gi"><h3>Energy landscape</h3><p>Pick a landscape, then click the surface. The ball follows the slope downhill. <b>Heat</b> shakes the ball hard and then cools it slowly (annealing), which can free it from traps.</p><div class="row"><button class="btn" id="d40">Drop 40 balls</button><button class="btn sec" id="ht">🔥 Heat: <span id="htv">off</span></button></div><p id="res" class="big" style="font-size:18px"></p></div></div>`,
init(w){const f=()=>{const n=+w.querySelector('#ln').value,s=+w.querySelector('#ls').value,r=+w.querySelector('#lr').value;w.querySelector('#lnv').textContent=n;w.querySelector('#lsv').textContent=s;w.querySelector('#lrv').textContent='10^'+r;const L=n*Math.log10(s);const ly=L-r-Math.log10(3.156e7),ou=ly-Math.log10(1.38e10);
  w.querySelector('#lo').innerHTML=`${s}<sup>${n}</sup> ≈ 10<sup>${L.toFixed(0)}</sup> possible shapes → trying them all takes ≈ 10<sup>${ly.toFixed(0)}</sup> years (${ou>0?'10<sup>'+ou.toFixed(0)+'</sup>× the age of the universe':'less than the age of the universe'}). <span class="ok">Real proteins fold in microseconds to seconds.</span>`};
 ['#ln','#ls','#lr'].forEach(s=>w.querySelector(s).oninput=f);f();
 let mode='rough',heat=0;const st=mkStage(w,{pos:[0,34,44],target:[0,0,0],auto:0,minD:12,maxD:90,onPick:hit=>{if(hit&&hit.point)drop(hit.point.x,hit.point.z)}});if(!st)return;addStars(st,150,90);
 const N=100;let mesh;function surf(){if(mesh){st.scene.remove(mesh);st.pick.length=0;mesh.geometry.dispose()}const g=new T.PlaneGeometry(38,38,N,N);g.rotateX(-Math.PI/2);const p=g.attributes.position,c=[];for(let i=0;i<p.count;i++){const y=h(mode,p.getX(i),p.getZ(i));p.setY(i,y);const t=clamp((y+1)/10,0,1);const col=new T.Color().setHSL(.62-t*.55,.8,.5);c.push(col.r,col.g,col.b)}g.setAttribute('color',new T.Float32BufferAttribute(c,3));g.computeVertexNormals();mesh=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness:.55,side:T.DoubleSide}));st.add(mesh,true);w.querySelectorAll('#lm .chip').forEach(b=>b.classList.toggle('on',b.dataset.k===mode))}
 const ball=sphereM(.9,'#ffffff',{em:'#ffffff',ei:.5});st.scene.add(ball);ball.visible=false;let bs=null;const trail=[];const tl=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xffffff}));st.scene.add(tl);
 function drop(x,z){bs={x,z,vx:0,vz:0,t:0};ball.visible=true;trail.length=0;w.querySelector('#res').textContent=''}
 st.up.push(dt=>{if(!bs)return;for(let k=0;k<3;k++){const[gx,gz]=grad(mode,bs.x,bs.z);const Tt=heat*Math.max(0,1-(bs.t*3+k)/900);bs.vx=bs.vx*.96-gx*.05+Tt*gauss()*.06;bs.vz=bs.vz*.96-gz*.05+Tt*gauss()*.06;bs.x=clamp(bs.x+bs.vx,-18.5,18.5);bs.z=clamp(bs.z+bs.vz,-18.5,18.5)}bs.t++;const y=h(mode,bs.x,bs.z)+.9;ball.position.set(bs.x,y,bs.z);if(bs.t%2===0){trail.push(new T.Vector3(bs.x,y,bs.z));if(trail.length>200)trail.shift();tl.geometry.setFromPoints(trail)}
  if(bs.t===500){const r=Math.hypot(bs.x,bs.z);w.querySelector('#res').innerHTML=r<2.5?'<span class="ok">Reached the native state!</span>':'<span class="no">Trapped in a local minimum (misfolded)</span>';react(r<2.5?'Native state found.':'Stuck!',r<2.5?'happy':'alert')}});
 [['golf','Random "golf course" (Levinthal)'],['funnel','Smooth funnel'],['rough','Rough funnel (realistic)']].forEach(([k,n])=>{const b=el('button','chip',n);b.dataset.k=k;b.onclick=()=>{mode=k;surf();bs=null;ball.visible=false;tl.geometry.setFromPoints([]);w.querySelector('#res').textContent='';react(n,'think')};w.querySelector('#lm').append(b)});
 w.querySelector('#ht').onclick=()=>{heat=heat?0:.8;w.querySelector('#htv').textContent=heat?'anneal':'off'};
 w.querySelector('#d40').onclick=()=>{let ok=0;for(let i=0;i<40;i++){let x=(Math.random()*2-1)*17,z=(Math.random()*2-1)*17,vx=0,vz=0;for(let n=0;n<1200;n++){const[gx,gz]=grad(mode,x,z);const Tt=heat*Math.max(0,1-n/900);vx=vx*.96-gx*.05+Tt*gauss()*.06;vz=vz*.96-gz*.05+Tt*gauss()*.06;x=clamp(x+vx,-18.5,18.5);z=clamp(z+vz,-18.5,18.5)}if(Math.hypot(x,z)<2.5)ok++}
  const m={golf:'random golf course',funnel:'smooth funnel',rough:'rough funnel'}[mode];w.querySelector('#res').innerHTML=`${ok} / 40 found the native state (${m}${heat?', with heat':''})`;react(`${ok}/40 folded.`,ok>30?'happy':'think')};
 surf()}});
})();

/* ===== g9: hydrophobic collapse sim ===== */
SCENES.push({id:'g9',belt:2,mood:'think',title:'Hydrophobic Collapse: Fold a Toy Chain',
html:`<p class="lead"><span style="color:#fb923c">● water-fearing</span> beads attract each other; <span style="color:#38bdf8">● water-loving</span> beads do not. Release the chain, change temperature, or <b>drag a bead</b> to poke it. Then add more chains to see aggregation.</p>
<div class="grid"><div class="card"><div class="row" id="gc"></div>${mkCv()}<div class="hint">Drag a bead to pull it · drag empty space to rotate</div></div><div class="card info"><h3>Controls</h3><div class="row"><button class="btn" id="rel">Release (unfold &amp; run)</button></div><label for="tp">Temperature: <b id="tpv"></b></label><input id="tp" type="range" min="0" max="150" value="35"><label for="hs">Hydrophobic attraction: <b id="hsv"></b></label><input id="hs" type="range" min="0" max="200" value="100"><h3 style="margin-top:10px">Readouts</h3><p id="rd" class="mini"></p><canvas id="sp" width="300" height="70" style="width:100%;height:70px;background:#050a22;border-radius:8px"></canvas><p class="mini">Orange–orange contacts over time. A single chain should plateau (a compact core); many chains can clump into aggregates instead, the basis of amyloid diseases.</p></div></div>`,
init(w){const SEQ='HPHPPHHPHHPPHPHHPPHPHHPHPPHHPHHPPHPH';const L=SEQ.length;let nc=1;const st=mkStage(w,{pos:[0,0,34],auto:.4,minD:8,maxD:100});if(!st)return;addStars(st,150,90);
 let n=L,pos,vel,isH,cid,tgtBead=-1,tgtPos=new T.Vector3(),T0=.35,HS=1,hist=[];let inst,lines,lg;
 function build(){if(inst){st.scene.remove(inst);st.scene.remove(lines);inst.geometry.dispose();lines.geometry.dispose()}n=L*nc;pos=new Float32Array(n*3);vel=new Float32Array(n*3);isH=[];cid=[];for(let c=0;c<nc;c++)for(let i=0;i<L;i++){isH.push(SEQ[i]==='H');cid.push(c)}
  inst=new T.InstancedMesh(new T.SphereGeometry(.5,14,10),new T.MeshStandardMaterial({roughness:.35}),n);inst.frustumCulled=false;st.scene.add(inst);const col=new T.Color();for(let i=0;i<n;i++)inst.setColorAt(i,col.set(isH[i]?'#fb923c':'#38bdf8'));
  lg=new T.BufferGeometry();lg.setAttribute('position',new T.BufferAttribute(new Float32Array((n)*6),3));lines=new T.LineSegments(lg,new T.LineBasicMaterial({color:0xcbd5e1}));lines.frustumCulled=false;st.scene.add(lines);release()}
 function release(){for(let c=0;c<nc;c++){const ox=(c%2)*14-7*(nc>1),oy=Math.floor(c/2)*12-6*(nc>2);for(let i=0;i<L;i++){const k=(c*L+i)*3;pos[k]=ox+(i-L/2)*.95+gauss()*.05;pos[k+1]=oy+Math.sin(i*.9)*.3;pos[k+2]=gauss()*.05+c*.3;vel[k]=vel[k+1]=vel[k+2]=0}}hist=[]}
 function step(dt){const eps=HS*1.6;const F=new Float32Array(n*3);
  for(let i=0;i<n;i++){const a=i*3;if(i+1<n&&cid[i]===cid[i+1]){const b=a+3;const dx=pos[b]-pos[a],dy=pos[b+1]-pos[a+1],dz=pos[b+2]-pos[a+2],d=Math.hypot(dx,dy,dz)||1e-3,f=60*(d-1)/d;F[a]+=f*dx;F[a+1]+=f*dy;F[a+2]+=f*dz;F[b]-=f*dx;F[b+1]-=f*dy;F[b+2]-=f*dz}
   for(let j=i+1;j<n;j++){const b=j*3,dx=pos[b]-pos[a],dy=pos[b+1]-pos[a+1],dz=pos[b+2]-pos[a+2],d2=dx*dx+dy*dy+dz*dz;if(d2>9)continue;const d=Math.sqrt(d2)||1e-3;let f=0;if(d<.95)f=-45*(.95-d)/d;else if(isH[i]&&isH[j]&&d<2.4)f=eps*(d<1.5?1:(2.4-d)/.9)/d;if(f){F[a]+=f*dx;F[a+1]+=f*dy;F[a+2]+=f*dz;F[b]-=f*dx;F[b+1]-=f*dy;F[b+2]-=f*dz}}
   const r=Math.hypot(pos[a],pos[a+1],pos[a+2]);if(r>18){const f=-1.5*(r-18)/r;F[a]+=f*pos[a];F[a+1]+=f*pos[a+1];F[a+2]+=f*pos[a+2]}}
  if(tgtBead>=0){const a=tgtBead*3;F[a]+=12*(tgtPos.x-pos[a]);F[a+1]+=12*(tgtPos.y-pos[a+1]);F[a+2]+=12*(tgtPos.z-pos[a+2])}
  const sd=Math.sqrt(2*T0*dt)*4;for(let k=0;k<n*3;k++){vel[k]=(vel[k]+F[k]*dt)*.88+gauss()*sd*.35;if(vel[k]>1.2)vel[k]=1.2;if(vel[k]<-1.2)vel[k]=-1.2;pos[k]+=vel[k]*dt*6}}
 const M4=new T.Matrix4(),P=new T.Vector3(),Sv=new T.Vector3(1,1,1),Qn=new T.Quaternion();let tick=0;
 st.up.push(dt=>{for(let s=0;s<4;s++)step(.025);for(let i=0;i<n;i++){P.set(pos[i*3],pos[i*3+1],pos[i*3+2]);M4.compose(P,Qn,Sv);inst.setMatrixAt(i,M4)}inst.instanceMatrix.needsUpdate=true;const a=lg.attributes.position.array;let q=0;for(let i=0;i+1<n;i++)if(cid[i]===cid[i+1]){a.set([pos[i*3],pos[i*3+1],pos[i*3+2],pos[i*3+3],pos[i*3+4],pos[i*3+5]],q);q+=6}lg.setDrawRange(0,q/3);lg.attributes.position.needsUpdate=true;
  if(++tick%8===0){let hh=0,ch=0;for(let i=0;i<n;i++){if(!isH[i])continue;for(let j=i+1;j<n;j++){if(!isH[j]||(cid[i]===cid[j]&&j-i<2))continue;const d=Math.hypot(pos[i*3]-pos[j*3],pos[i*3+1]-pos[j*3+1],pos[i*3+2]-pos[j*3+2]);if(d<1.3){hh++;if(cid[i]!==cid[j])ch++}}}hist.push(hh);if(hist.length>150)hist.shift();draw(hh,ch)}});
 const cvs=w.querySelector('#sp').getContext('2d');function draw(hh,ch){cvs.clearRect(0,0,300,70);cvs.strokeStyle='#fb923c';cvs.lineWidth=2;cvs.beginPath();const mx=Math.max(20,...hist);hist.forEach((v,i)=>{const x=i/150*300,y=68-v/mx*64;i?cvs.lineTo(x,y):cvs.moveTo(x,y)});cvs.stroke();
  let cx=0,cy=0,cz=0,nh=0;for(let i=0;i<n;i++)if(isH[i]){cx+=pos[i*3];cy+=pos[i*3+1];cz+=pos[i*3+2];nh++}cx/=nh;cy/=nh;cz/=nh;let dH=0,dP=0,pH=0;for(let i=0;i<n;i++){const d=Math.hypot(pos[i*3]-cx,pos[i*3+1]-cy,pos[i*3+2]-cz);if(isH[i]){dH+=d}else{dP+=d;pH++}}
  w.querySelector('#rd').innerHTML=`H–H contacts: <b>${hh}</b>${nc>1?` (between different chains: <b>${ch}</b>)`:''}<br>mean distance from H-centroid: orange ${(dH/nh).toFixed(1)}, blue ${(dP/pH).toFixed(1)} → ${nc>1&&ch>hh*.2?'<span class="no">chains are sticking to each other (aggregation)</span>':dP/pH>dH/nh*1.25?'<span class="ok">a hydrophobic core has formed</span>':'still unfolded / mixed'}`}
 const cv=w.querySelector('canvas');cv.addEventListener('pointerdown',e=>{const r=cv.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let best=-1,bd=18;const v=new T.Vector3();for(let i=0;i<n;i++){v.set(pos[i*3],pos[i*3+1],pos[i*3+2]).project(st.cam);const d=Math.hypot((v.x+1)/2*r.width-mx,(1-v.y)/2*r.height-my);if(d<bd){bd=d;best=i}}if(best>=0){e.stopImmediatePropagation();tgtBead=best;cv.setPointerCapture(e.pointerId);move(e)}},true);
 function move(e){if(tgtBead<0)return;const r=cv.getBoundingClientRect();const v=new T.Vector3(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1,.5).unproject(st.cam);const dir=v.sub(st.cam.position).normalize();const cur=new T.Vector3(pos[tgtBead*3],pos[tgtBead*3+1],pos[tgtBead*3+2]);const d=cur.clone().sub(st.cam.position).dot(st.cam.getWorldDirection(new T.Vector3()))/dir.dot(st.cam.getWorldDirection(new T.Vector3()));tgtPos.copy(st.cam.position).addScaledVector(dir,d)}
 cv.addEventListener('pointermove',move);cv.addEventListener('pointerup',()=>{tgtBead=-1});
 w.querySelector('#tp').oninput=e=>{T0=e.target.value/100;w.querySelector('#tpv').textContent=T0.toFixed(2)};w.querySelector('#hs').oninput=e=>{HS=e.target.value/100;w.querySelector('#hsv').textContent=HS.toFixed(2)};w.querySelector('#tp').oninput({target:w.querySelector('#tp')});w.querySelector('#hs').oninput({target:w.querySelector('#hs')});
 w.querySelector('#rel').onclick=()=>{release();react('Released! Watch the orange beads huddle.','happy')};
 [1,2,4].forEach(k=>{const b=el('button','chip'+(k===1?' on':''),k+(k===1?' chain':' chains'));b.onclick=()=>{nc=k;w.querySelectorAll('#gc .chip').forEach(x=>x.classList.toggle('on',x===b));build();react(k>1?'More chains: watch for clumping between chains.':'One chain.','think')};w.querySelector('#gc').append(b)});
 build()}});

/* ===== g10: misfolding ===== */
SCENES.push({id:'g10',belt:2,mood:'alert',title:'When Folding Goes Wrong',
html:`<p class="lead">Two stories. <b>Sickle cell</b>: one amino acid swap on the surface of hemoglobin. <b>Amyloid</b>: normal proteins refolding into stacked β-sheets.</p>
<div class="grid"><div class="card"><div class="row" id="tb"></div>${mkCv()}</div><div class="card info" id="gi"></div></div>`,
init(w){const gi=w.querySelector('#gi');let tab='sickle',st=null,mut=false,nl=6;
 function sickle(){const S=STRUCT['2HHB'];st=mkStage(w,{pos:[0,0,90],auto:.3,minD:4,maxD:200});if(!st)return;addStars(st,150,300);const pv=new ProteinView(st,S,{chains:['A','B','C','D'],mode:'chain'});fitCamera(st,pv,2.3);st.up.push(()=>pv.update());
  const bs=['B','D'].map(id=>pv.chains.find(c=>c.id===id)),pts=bs.map(c=>{const i=c.res.findIndex(r=>r.n===6);return{c,i,p:c.nat[i]}});const spheres=pts.map(q=>{const s=sphereM(2.6,'#ef4444',{em:'#ef4444',ei:.5,op:.8});s.position.set(...q.p);st.scene.add(s);return s});
  const extra=[];[85,88].forEach(n=>{pts.forEach(q=>{const i=q.c.res.findIndex(r=>r.n===n);if(i>=0){const s=sphereM(1.6,'#fbbf24',{em:'#fbbf24',ei:.3,op:.7});s.position.set(...q.c.nat[i]);s.visible=false;st.scene.add(s);extra.push(s)}})});
  const upd=()=>{spheres.forEach(s=>{s.material.color.set(mut?'#fbbf24':'#ef4444');s.material.emissive.set(mut?'#fbbf24':'#ef4444')});extra.forEach(s=>s.visible=mut);const aa6=pts[0].c.res[pts[0].i];
   gi.innerHTML=infoBox('Sickle cell: β6 Glu → Val',`The two big spheres mark residue 6 of each β chain (currently <b>${mut?'Val (water-fearing)':AAFULL[aa6.aa]+' (acidic, charged)'}</b>), the position changed by <b>one DNA letter (GAG → GTG)</b>.<p>${mut?'In deoxygenated HbS, the Val sticks into a hydrophobic pocket on a neighbouring hemoglobin (formed by Phe85 and Leu88, yellow). Molecules stack into long fibres that distort red blood cells into crescents.':'Glu6 is on the surface and is harmless: it faces water.'}</p><div class="row"><button class="btn" id="mt">${mut?'Restore Glu':'Mutate to Val'}</button><button class="btn sec" id="fc">Focus on β6</button></div><p class="mini">Heterozygous carriers (one HbS allele) are usually healthy and are partly protected from malaria.</p>`);
   gi.querySelector('#mt').onclick=()=>{mut=!mut;upd();react(mut?'One letter, one amino acid, a sticky patch.':'Back to normal.','alert')};gi.querySelector('#fc').onclick=()=>st.focus(pts[0].p,18,.8)};upd()}
 function fibril(){st=mkStage(w,{pos:[16,26,20],target:[0,0,0],auto:.5,minD:8,maxD:100});if(!st)return;addStars(st,150,200);const grp=new T.Group();st.scene.add(grp);const lines=new T.Group();grp.add(lines);let n=0,tgt=8;const mats=[];
  const L=[];const make=i=>{const g=new T.Group();[-1.7,1.7].forEach((x,s)=>{const sh=new T.Group();const body=new T.Mesh(new T.BoxGeometry(5,.35,1.3),new T.MeshStandardMaterial({color:s?'#fbbf24':'#f472b6',roughness:.4}));body.position.x=-.4;const head=new T.Mesh(new T.ConeGeometry(1.1,1.6,3),body.material);head.rotation.z=-Math.PI/2;head.position.x=3.1;head.scale.set(1,1,.35);sh.add(body,head);sh.position.set(0,x,0);g.add(sh)});g.position.z=-i*1.5;g.userData.i=i;return g};
  const sync=()=>{while(L.length<tgt){const g=make(L.length);g.scale.setScalar(.01);grp.add(g);L.push(g)}};
  const hb=new T.LineSegments(new T.BufferGeometry(),new T.LineBasicMaterial({color:0x9db3d8,transparent:true,opacity:.6}));grp.add(hb);
  st.up.push(()=>{sync();L.forEach(g=>g.scale.setScalar(Math.min(1,g.scale.x+.04)));const a=[];for(let i=1;i<L.length;i++)for(const y of[-1.7,1.7])for(const x of[-2.2,-.4,1.4])a.push(x,y,-(i-1)*1.5,x,y,-i*1.5);hb.geometry.setAttribute('position',new T.Float32BufferAttribute(a,3));grp.position.z=(L.length-1)*.75});
  gi.innerHTML=infoBox('Amyloid fibrils: cross-β structure',`In a fibril, β-strands run <b>perpendicular</b> to the fibre axis, and hydrogen bonds (thin lines) link each copy to the next along the axis. Two sheets pack against each other. Once a seed forms, it recruits more copies, like a crystal growing.<p><b>Examples:</b> amyloid-β and tau (Alzheimer's), α-synuclein (Parkinson's), prion protein (Creutzfeldt–Jakob disease). Fibrils are extremely stable, which makes them hard for cells to clear.</p><div class="row"><button class="btn" id="ad">+ Add 4 monomers</button><button class="btn sec" id="rs">Reset</button></div><p class="mini">Cartoon, not to scale. Amyloid-like folds can also be functional (some bacteria and fungi use them on purpose).</p>`);
  gi.querySelector('#ad').onclick=()=>{tgt+=4;react('Fibril grows: '+tgt+' layers.','think')};gi.querySelector('#rs').onclick=()=>{L.forEach(g=>grp.remove(g));L.length=0;tgt=8}}
 function show(t){tab=t;if(st){st.destroy();st=null}const oc=w.querySelector('canvas');oc.replaceWith(oc.cloneNode(false));mut=false;w.querySelectorAll('#tb .chip').forEach(b=>b.classList.toggle('on',b.dataset.k===t));t==='sickle'?sickle():fibril()}
 [['sickle','Sickle cell (hemoglobin)'],['amy','Amyloid fibril']].forEach(([k,n])=>{const b=el('button','chip',n);b.dataset.k=k;b.onclick=()=>show(k);w.querySelector('#tb').append(b)});show('sickle')}});
